# Generated by Django 2.2.3 on 2019-07-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ven_info',
            },
        ),
        migrations.CreateModel(
            name='RainySeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('active', models.BooleanField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidwear.Vendor')),
            ],
            options={
                'db_table': 'cloths_info',
            },
        ),
    ]
